#!/bin/bash

# Go to my own directory
MY_DIR=$(dirname "$0")
cd "${MY_DIR}"
MY_DIR=$(pwd -P)

# Load image settings
source ../settings/images

# Check command line
if [[ "$1" != [1-2] ]]; then
        echo "======================"
        echo "|| IPv6 Core Switch ||"
        echo "======================"
        echo "Usage:"
        echo -e "\t$0 <Server-nr>"
        echo ""
        echo "Where <Server-nr> is either 1 or 2"
	exit 1
fi

TRANSIT="$1"
DIR="../working/TRANSIT${TRANSIT}"
DYNAMIPS_PORT=$((7010 + ${TRANSIT}))

echo "---------------------------------------------"
echo "- Starting Dynamips Hypervisor on port ${DYNAMIPS_PORT} -"
echo "---------------------------------------------"

mkdir -p "${DIR}"
cd "${DIR}"
../../bin/dynamips-0.2.8-RC3-community-OSX.intel64.bin -H ${DYNAMIPS_PORT} --filepid dynamips.pid &> dynamips.out &
cd "${MY_DIR}"

sleep 1

echo -n "PID: "
cat "${DIR}/dynamips.pid"
echo ""

echo ""
echo "--------------------------------------------------------"
echo "- Generating Dynagen configuration for transit routers -"
echo "--------------------------------------------------------"

sed -e "s/\${C7200_IMAGE}/${C7200_IMAGE}/g" \
    -e "s/\${C7200_IDLEPC}/${C7200_IDLEPC}/g" \
    -e "s/\${C7200_RAM}/${C7200_RAM}/g" \
    -e "s/\${DYNAMIPS_PORT}/${DYNAMIPS_PORT}/g" \
    -e "s/\${TRANSIT}/${TRANSIT}/g" \
    < topology-template.net \
    > "${DIR}/transit-router.net"

echo ""
echo "------------------------------------------------------"
echo "- Starting Dynagen with transit router configuration -"
echo "------------------------------------------------------"

../bin/dynagen/dynagen "${DIR}/transit-router.net"

echo ""
echo "---------------------------------------------"
echo "- Stopping Dynamips Hypervisor on port ${DYNAMIPS_PORT} -"
echo "---------------------------------------------"

kill `cat "${DIR}/dynamips.pid"`

echo -n "Killed PID: "
cat "${DIR}/dynamips.pid"
echo ""

rm -f "${DIR}/dynamips.pid"

echo ""
