#!/bin/bash

# Calculate the margind
MARGIN_TOP=22
MARGIN_LEFT=0
MARGIN_RIGHT=0
MARGIN_BOTTOM=0

DOCK_ORIENTATION="$(defaults read com.apple.dock orientation 2>/dev/null)"
DOCK_SIZE="$(defaults read com.apple.dock tilesize)"
DOCK_SIZE=${DOCK_SIZE/.*}
DOCK_SIZE=$((DOCK_SIZE+20))

if [ "${DOCK_ORIENTATION}" = "left" ]; then
	MARGIN_LEFT="${DOCK_SIZE}"
elif [ "${DOCK_ORIENTATION}" = "right" ]; then
	MARGIN_RIGHT="${DOCK_SIZE}"
else
	MARGIN_BOTTOM="${DOCK_SIZE}"
fi

# Go to my own directory
MY_DIR=$(dirname "$0")
cd "${MY_DIR}"
MY_DIR=$(pwd -P)

# Check command line
if [[ "$1" != [1-9] || "$2" != [1-3] || ( "$3" != "make" && "$3" != "run" && "$3" != "both" && "$3" != "" ) ]]; then
	echo "========================"
	echo "|| IPv6 LAB Generator ||"
	echo "========================"
	echo "Usage:"
	echo -e "\t$0 <POP-count> <Server-nr> [make|run|both]"
	echo ""
	echo "Where <POP-count> is a number from 1 to 9"
	echo "Where <Server-nr> is either 1, 2 or 3"
	echo ""
	echo -e "\tWhen the LAB is completely done you can remove the 'working' directory"
	echo -e "\tto get rid of all configurations"
	echo ""
	exit 1
fi

POP_COUNT="$1"
SERVER_NR="$2"
ACTION="$3"

# Set default
if [ "${ACTION}" = "" ]; then
	ACTION="both"
fi

# Get node settings
source ./settings/nodes

# Get local IP
MY_IP_VAR="NODE${SERVER_NR}_IP"
MY_IP="${!MY_IP_VAR}"

# Calculate number of POPs
LOCAL_POP_COUNT=0
LOCAL_POPS=""
for POP in `seq 1 ${POP_COUNT}`; do
	POP_VAR="POP${POP}_IP"
	if [ "${!POP_VAR}" = "${MY_IP}" ]; then
		LOCAL_POP_COUNT=$((LOCAL_POP_COUNT + 1))
		LOCAL_POPS="${LOCAL_POPS} ${POP}"
	fi
done

# Determine if we run switches
LOCAL_SWITCHES=""
if [ "${MY_IP}" = "${SW1_IP}" ]; then
	LOCAL_SWITCHES="${LOCAL_SWITCHES} 1"
fi
if [ "${MY_IP}" = "${SW2_IP}" ]; then
	LOCAL_SWITCHES="${LOCAL_SWITCHES} 2"
fi

# Determine if we run transits
LOCAL_TRANSITS=""
if [ "${MY_IP}" = "${TRANSIT1_IP}" ]; then
	LOCAL_TRANSITS="${LOCAL_TRANSITS} 1"
fi
if [ "${MY_IP}" = "${TRANSIT2_IP}" ]; then
	LOCAL_TRANSITS="${LOCAL_TRANSITS} 2"
fi

# We show two POPs side by side
# This rounds up
POP_ROWS=$(( (${LOCAL_POP_COUNT} + 1) / 2 ))

# Generate configs
if [ "${ACTION}" = "make" -o "${ACTION}" = "both" ]; then
	./cfg-generator/generate v4 "${POP_COUNT}"
	./cfg-generator/generate v6 "${POP_COUNT}"
	./cfg-generator/generate dual "${POP_COUNT}"
	./cfg-generator/generate pre-6rd "${POP_COUNT}"
	./cfg-generator/generate 6rd "${POP_COUNT}"
fi

# Stop, unless we want to run
if [ "${ACTION}" != "run" -a "${ACTION}" != "both" ]; then
	exit
fi

echo "-------------------------------------"
echo "- Starting lab sections with ${POP_COUNT} POPs -"
echo "- Local server runs ${LOCAL_POP_COUNT} POPs          -"
echo "-------------------------------------"

# Get screen dimensions
DESKTOP_WIDTH=$(osascript -e "tell application \"Finder\" to set _b to bounds of window of desktop" -e "get item 3 of _b")
DESKTOP_HEIGHT=$(osascript -e "tell application \"Finder\" to set _b to bounds of window of desktop" -e "get item 4 of _b")

WINDOW_WIDTH=$(( (${DESKTOP_WIDTH} - ${MARGIN_LEFT} - ${MARGIN_RIGHT}) / 2 ))
WINDOW_WIDTH_NARROW=$(( (${DESKTOP_WIDTH} - ${MARGIN_LEFT} - ${MARGIN_RIGHT}) / 3 ))
WINDOW_HEIGHT=$(( (${DESKTOP_HEIGHT} - ${MARGIN_TOP} - ${MARGIN_BOTTOM}) / (${POP_ROWS} + 1) ))

# Move this window to top left
osascript -e "tell application\"Terminal\" to set the bounds of its front window to {${MARGIN_LEFT}, ${MARGIN_TOP}, $(( ${MARGIN_LEFT} + ${WINDOW_WIDTH_NARROW} )), $(( ${MARGIN_TOP} + ${WINDOW_HEIGHT} ))}"

for SWITCH in ${LOCAL_SWITCHES}; do
	# Start Core Switches
	WIN_ID=$(osascript -e "tell application \"Terminal\" to do script \"${MY_DIR}/core-switches/run ${SWITCH}; exit\"" | cut -d ' ' -f 6)
	osascript -e "tell application \"Terminal\" to tell window id ${WIN_ID} to tell its selected tab to set its custom title to \"Core-Switch ${SWITCH}\""

	# Move this window to top right
	osascript -e "tell application\"Terminal\" to set the bounds of window id ${WIN_ID} to {$(( ${MARGIN_LEFT} + ${WINDOW_WIDTH_NARROW} )), ${MARGIN_TOP}, $(( ${MARGIN_LEFT} + 2 * ${WINDOW_WIDTH_NARROW} )), $(( ${MARGIN_TOP} + ${WINDOW_HEIGHT} ))}"
done

for TRANSIT in ${LOCAL_TRANSITS}; do
	# Start Transit Routers
	WIN_ID=$(osascript -e "tell application \"Terminal\" to do script \"${MY_DIR}/transit-routers/run ${TRANSIT}; exit\"" | cut -d ' ' -f 6)
	osascript -e "tell application \"Terminal\" to tell window id ${WIN_ID} to tell its selected tab to set its custom title to \"Transit-Router ${TRANSIT}\""

	# Move this window to top right
	osascript -e "tell application\"Terminal\" to set the bounds of window id ${WIN_ID} to {$(( ${MARGIN_LEFT} + 2 * ${WINDOW_WIDTH_NARROW} )), ${MARGIN_TOP}, $(( ${MARGIN_LEFT} + 3 * ${WINDOW_WIDTH_NARROW} )), $(( ${MARGIN_TOP} + ${WINDOW_HEIGHT} ))}"
done

PLACEMENT="left"
ROW=1
for POP in ${LOCAL_POPS}; do
	# Start the POP Routers
	WIN_ID=$(osascript -e "tell application \"Terminal\" to do script \"${MY_DIR}/pop-routers/run ${POP}; exit\"" | cut -d ' ' -f 6)
	osascript -e "tell application \"Terminal\" to tell window id ${WIN_ID} to tell its selected tab to set its custom title to \"POP${POP} Routers\""

	if [ "${PLACEMENT}" = "left" ]; then
		# Move this window to the left
		osascript -e "tell application\"Terminal\" to set the bounds of window id ${WIN_ID} to {${MARGIN_LEFT}, $(( ${MARGIN_TOP} + ${ROW} * ${WINDOW_HEIGHT} )), $(( ${MARGIN_LEFT} + ${WINDOW_WIDTH} )), $(( ${MARGIN_TOP} + (${ROW}+1) * ${WINDOW_HEIGHT} ))}"
		
		PLACEMENT="right"
	else
		# Move this window to the right
		osascript -e "tell application\"Terminal\" to set the bounds of window id ${WIN_ID} to {$(( ${MARGIN_LEFT} + ${WINDOW_WIDTH} )), $(( ${MARGIN_TOP} + ${ROW} * ${WINDOW_HEIGHT} )), $(( ${MARGIN_LEFT} + 2 * ${WINDOW_WIDTH} )), $(( ${MARGIN_TOP} + (${ROW}+1) * ${WINDOW_HEIGHT} ))}"
		
		PLACEMENT="left"
		ROW=$((ROW+1))
	fi
done

#top -u
